[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'osyo-manga/vim-precious'
depends = ['context_filetype.vim']

[[plugins]] # カーソル位置のコンテキストのftを判定するライブラリ
repo = 'Shougo/context_filetype.vim'

[[plugins]] # toml syntax
repo = 'cespare/vim-toml'
on_ft = 'toml'

[[plugins]] # カラースキーマ
repo = 'w0ng/vim-hybrid'
hook_add = '''
  set background=dark
  " colorscheme 設定は source 後に行う必要があるので VimEnter で行う。
  " 但し Colorscheme イベントの発生が抑制されないよう nented を付ける。
  au MyAutoCmd VimEnter * nested colorscheme hybrid
'''

[[plugins]] # コード補完
repo = 'Shougo/deoplete.nvim'
if = 'has("nvim")'
on_i = 1
hook_add = '''
  let g:deoplete#enable_at_startup = 1
  let g:deoplete#enable_smart_case = 1
  let g:deoplete#sources#go#package_dot = 1
  "set completeopt-=preview " プレビューウィンドウを開かないようにする
  "set completeopt+=noinsert " 最初の候補がデフォで選択されるようにする
  " TAB や Shift-TAB で補完補完候補を上下する
  if ! dein#tap('neosnippet.vim')
    " neosnippet使う場合はそっちも考慮した設定をしてるのでスキップ
    inoremap <expr><TAB>  pumvisible() ? "\<C-n>" : "\<TAB>"
  endif
  inoremap <expr><S-TAB>  pumvisible() ? "\<C-p>" : "\<S-TAB>"
  inoremap <expr><UP>   pumvisible() ? "\<C-p>" : "<UP>"
  inoremap <expr><DOWN> pumvisible() ? "\<C-n>" : "<DOWN>"
  " python3が無かったらメッセージを表示
  if has('nvim') && !has('python3')
    echo "require python3 https://gist.github.com/kawaz/393c7f62fe6e857cc3d9 or execute 'pip3 install neovim --upgrade' and :call dein#update()"
  endif
'''

[[plugins]]
repo = 'Shougo/neosnippet-snippets'

# Javascript
[[plugins]]
repo = 'pangloss/vim-javascript'
on_ft = ['javascript']
hook_add = '''
  let g:javascript_plugin_jsdoc = 1
  let g:javascript_plugin_ngdoc = 1
  let g:javascript_plugin_flow = 1
'''

[[plugins]]
repo = 'mxw/vim-jsx'
on_ft = ['javascript']
hook_add = '''
  " 拡張子が.jsでも効くようにする(デフォルトは.jsxのみ)
  let g:jsx_ext_required = 0
'''

[[plugins]]
repo = 'scrooloose/nerdtree'
hook_add='''
  let g:NERDTreeAutoCenter=1
  let g:NERDTreeShowBookmarks=1
  let g:NERDTreeWinSize=25
  let g:NERDTreeShowHidden=0 "隠しフォルダは表示しない
  let  NERDTreeIgnore =
    \ ['\.pyc', '\.git$', '\^~$', '\node_modules', '\.DS_Store']
  nnoremap <C-n> :NERDTreeToggle<CR>
  vnoremap <C-n> :NERDTreeToggle<CR>
  inoremap <C-n> :NERDTreeToggle<CR>
  cnoremap <C-n> :NERDTreeToggle<CR>
  "au MyAutoCmd VimEnter * NERDTree
'''

##設定がうまくいかないので保留
#[[plugins]]
#repo = 'ryanoasis/vim-devicons'
#depends = ['scrooloose/nerdtree']
#hook_add = '''
#  set guifont=Droid\ Sans\ Mono\ for\ Powerline\ Plus\ Nerd\ File\ Types\ 11
#  let g:WebDevIconsUnicodeDecorateFolderNodes = 1
#'''
#
#[[plugins]]
#repo = 'tiagofumo/vim-nerdtree-syntax-highlight'
#depends = ['scrooloose/nerdtree']
#hock_add='''
#  let g:NERDTreeIndicatorMapCustom = {
#    \ "Modified"  : "✹",
#    \ "Staged"    : "✚",
#    \ "Untracked" : "✭",
#    \ "Renamed"   : "➜",
#    \ "Unmerged"  : "═",
#    \ "Deleted"   : "✖",
#    \ "Dirty"     : "✗",
#    \ "Clean"     : "✔︎",
#    \ 'Ignored'   : '☒',
#    \ "Unknown"   : "?"
#    \ }
#'''

[[plugins]]
repo = 'tpope/vim-fugitive'

[[plugins]]
repo = 'airblade/vim-gitgutter'

